### ISSUE TITLE
ActionMailer Configs

### ISSUE THREAD

**Issue by BrandonMathis** [smashingboxes/boxcar-generator-archive#48]
Needs `config.action_mailer.default_url_options = { host: 'localhost:3000' }` set in `config/environments/test.rb`.

**Comment by dkniffin** [comment]
Also needs letter_opener in development

```rb
# Gemfile
group :development do
  gem "letter_opener"
end
```

```rb
# config/environments/development.rb
config.action_mailer.delivery_method = :letter_opener
config.action_mailer.perform_deliveries = true
```

and mailgun in production

```rb
# Gemfile
gem "mailgun_rails"
```

```rb
# config/environments/production.rb
config.action_mailer.default_url_options = { host: Rails.application.secrets.mailgun_domain }

config.action_mailer.delivery_method = :mailgun

config.action_mailer.mailgun_settings = {
  api_key: Rails.application.secrets.mailgun_api_key,
  domain: Rails.application.secrets.mailgun_domain
}
```

```yml
# secrets.example.yml or secrets.yml

production:
  mailgun_api_key: <%= ENV["MAILGUN_API_KEY"] %>
  mailgun_domain: <%= ENV["MAILGUN_DOMAIN"] %>
```
