### ISSUE TITLE
Style/RegexpLiteral

### ISSUE THREAD

**Issue by dkniffin** [smashingboxes/boxcar-generator-archive#61]
Right now, we're not allowing multi-line regexes with `%r{...}x`. We should allow it with this config:

```yml
Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: false
```
